###*
# Created by david-maser on 28/10/15.
###

(($) ->

  $.fn.filterize = (options) ->
    # This is the easiest way to have default options.
    settings = $.extend({
      blur: null
      brightness: null
      contrast: null
      dropShadow: null
      grayscale: null
      hueRotate: null
      invert: null
      opacity: null
      saturate: null
      sepia: null
      transition: 1
      mode: null
    }, options)
    r = navigator
    pool = ''
    pref = ''
    nav = r.appName
    prod = r.product
    isOpera = ! !window.opera or navigator.userAgent.indexOf(' OPR/') >= 0
    isFirefox = typeof InstallTrigger != 'undefined'
    isSafari = Object::toString.call(window.HTMLElement).indexOf('Constructor') > 0
    isChrome = ! !window.chrome and !isOpera
    isIE = false or ! !document.documentMode
    if isChrome == true or isSafari == true
      pref = '-webkit-'
    else if isFirefox == true
      pref = '-moz-'
    console.log options
    # filterize the collection based on the settings variable.
    if settings.blur != null
      pool += 'blur(' + settings.blur + 'px) '
    if settings.brightness != null
      pool += 'brightness(' + settings.brightness + ') '
    if settings.contrast != null
      pool += 'contrast(' + settings.contrast + ') '
    if settings.dropShadow != null
      pool += 'drop-shadow(' + settings.dropShadow + ') '
    if settings.grayscale != null
      pool += 'grayscale(' + settings.grayscale + ') '
    if settings.hueRotate != null
      pool += 'hue-rotate(' + settings.hueRotate + 'deg) '
    if settings.invert != null
      pool += 'invert(' + settings.invert + ') '
    if settings.opacity != null
      pool += 'opacity(' + settings.opacity + ') '
    if settings.saturate != null
      pool += 'saturate(' + settings.saturate + ') '
    if settings.sepia != null
      pool += 'sepia(' + settings.sepia + ') '
    if settings.mode == 'style'
      return @css(
        'filter': pool
        '-webkit-filter': pool
        '-moz-filter': pool)
    else if settings.mode == 'hover'
      $(this).on('mouseover', ->
        $(this).css
          'filter': pool
          '-webkit-filter': pool
          '-moz-filter': pool
        return
      ).on 'mouseout', ->
        $(this).attr('style', '').css 'transition', settings.transition + 's'
        return
      return @css('transition', settings.transition + 's')
    return

  return
) jQuery

###*
 usage
 $( "div" ).filterize({
    blur:2,
    brightness:2,
    sepia:1
 });
#
###

# ---
# generated by js2coffee 2.2.0
